name: Build yogger
description: Build yogger
runs:
  using: composite
  steps:
    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
      shell: bash -el {0}

    - name: Build Yogger
      run: |
        python -m pip install -e . --no-build-isolation --no-index
      shell: bash -el {0}
